FROM alpine:3

LABEL author="Fauzan Maftuh Alwafi"
LABEL company="Institut Teknologi Kalimantan" website="https://www.programmerzamannow.com"

RUN mkdir hello 
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"